# Python vanuit Jupyter notebooks

Dit notebook is onderdeel van een serie van 3 x 4 notebooks, die horen bij de introductiecursus Python voor data science. Deze beslaat 4 avonden die ieder hun eigen thema hebben:

1.) **Een introductie** tot de programmeertaal **Python** en de **Jupyter** Notebooks/Labs waarin we Python gebruiken.

2.) Werken met **data** in Python. Data science heet data science omdat het over data gaat. Dus het lezen, bewerken en verwerken van data staat voorop.

3.) **Visualisatie**. Niet alleen omdat het je resultaten mooi en overzichtelijk weergeeft, maar ook omdat je je data beter leert begrijpen.

4.) **Machine learning** is tegenwoordig niet meer weg te denken uit de toolbox van de data scientist, dus een gedegen introductie tot dit waanzinnig interessante vakgebied kan niet ontbreken!

Voor elk van de onderdelen bestaat een instructie notebook. Deze gaat vergezeld door een presentatie tijdens de cursus en kan gebruikt worden als naslagwerk, om te zien hoe bepaalde dingen werken en, als je wil, ook om daarmee te experimenteren. Het is vaak kort en bondig, maar geeft je wellicht genoeg houvast om met de documentatie binnen Python en online op gang te komen. De opgaven in de corresponderende notebooks zijn opgaven die de stof uit de instructienotebooks verrijken. Die zullen grotendeels op de cursusavonden gedaan worden, maar het is aan te raden om deze thuis ook te bekijken, om te zorgen dat je niks mist. De huiswerknotebooks bevatten nog extra opgaven voor als je meer wil oefenen. Daarnaast bevatten ze wat extra uitdaging voor wie daar aan toe is. Veel van de onderwerpen die we behandelen in de 4 cursusbijeenkomsten zijn slechts het topje van de ijsberg waar het neerkomt op diepgang van het materiaal en de extra opgaven geven je een indruk van wat er nog meer achter de horizon ligt.

De series met opgaven en huiswerk bevatten dus een hoop opgaven. Zelden heeft een opgave slechts 1 correct antwoord. Je kunt dingen oplossen zoals je zelf wil. Mocht je vastlopen, je uitwerkingen willen controleren, of zien hoe ik de opgave zou hebben aangepakt, dan zijn er uitwerkingen beschikbaar. Deze zijn in het notebook in te laden en geven je een manier van aanpakken van de opgave in een cell die je zo moet kunnen uitvoeren. Wil je feedback op je eigen methode of heb je nog vragen over, schroom dan niet om deze te mailen naar datascience@marcelhaas.com.

Veel plezier!


## Python als handig rekenhulpmiddel

Vanuit een notebook, of vanuit welke omgeving je Python dan ook gebruikt, kun je korte eenvoudige opdrachten geven die direct een resultaat opleveren. Regels die beginnen met een # zijn "commentaar" en worden door Python genegeerd. Wanneer je ctrl-enter indrukt worden de opdrachten die in de betreffende cell staan uitgevoerd. Druk je shift-enter dan gebeurt datzelfde en ga je door naar de volgende cell.

In [1]:
# Deze regel doet dus verder niks. Ik kan hier wel zeggen dat ik in de komende regel een simpele optelling ga doen.
3+4

7

Zoals je ziet voert Python braaf je rekensommetje uit en geeft hij het antwoord direct onder de code waar je staat. Het tonen van het resultaat gebeurt echter wel alleen voor de laatste regel. Dingen die in andere regels staan gebeuren wel, maar omdat Python nog niet klaar is met al je opdrachten wordt er niks getoond, behalve als dat expliciet gezegd wordt:

In [19]:
3+2
a = 2**4
print(2+6)
44
3*7
print("a =", a)
1+8

8
a = 16


9

Ook na het uitvoeren van de cell weet Python nog wat gedefinieerde variabelen inhouden:

In [20]:
a

16

## Strings, indexing en het gebruik van functies

In Python kun je niet alleen met getallen werken, maar ook met strings: tekst. We gebruiken strings hier om te kijken naar hoe Python omgaat met indices en hoe je functies gebruikt.

In [1]:
mijn_eerste_string = "Python is echt heel leuk!"

In [2]:
# Deze string kun je in je scherm laten printen
print(mijn_eerste_string)

Python is echt heel leuk!


Indexering in Python is 0-based, dus het eerste element heeft index 0, het tweede 1 en zo verder. Met negatieve indices tel je de andere kant op, zodat index -1 overeenkomt met het laatste getal. Deze methode werkt voor strings, maar ook voor "containers" van data zoals we die verderop zullen zien. Voorbeelden:

In [10]:
print("Het eerste teken in de string heeft index 0 en is", mijn_eerste_string[0])
print("Het laatste teken in de string heeft index -1 (of de lengte van de string -1) en is", mijn_eerste_string[-1], mijn_eerste_string[len(mijn_eerste_string)-1])

Het eerste teken in de string heeft index 0 en is P
Het laatste teken in de string heeft index -1 (of de lengte van de string -1) en is ! !


Slicing is het nemen van een stuk van de string, en wordt gegeven door een begin en eindpunt gescheiden door een dubbele punt (:). Het eindpunt zelf wordt *niet* meegenomen. De stapgrootte kun je aangeven achter nog een dubbele punt, deze is standaard uiteraard 1:

In [9]:
print("Het eerste teken in de string heeft index 0. Die en alle even elementen zijn", mijn_eerste_string[0::2])
print("Juist alle oneven vind je zo:", mijn_eerste_string[1::2])
print("Van element 2 tot en met 11 in stapjes van 3:", mijn_eerste_string[2:12:3])

Het eerste teken in de string heeft index 0. Die en alle even elementen zijn Pto seh ellu!
Juist alle oneven vind je zo: yhni cthe ek
Van element 2 tot en met 11 in stapjes van 3: tnsc


Je ziet hier veevuldig het gebruik van print(). Zo'n statement dat eindigt op haakjes, al dan niet met iets ertussen is een **functie**. Zo er bestaan er nog veel meer. 

## In Python zitten functionaliteiten om je te helpen en de documentatie te raadplegen ingebouwd.

De help functionaliteiten van Python zijn direct vanuit notebooks toegankelijk. Zo kun je alt-tab indrukken als je tussen de haakjes van de functie staat, of op de volgende manier de help raadplegen: 

In [11]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


Zoals je ziet staat daar precies hoe je hem kunt aanroepen, wat je extra opties zijn en wat de functie dan gaat doen. Maak hier gebruik van tijdens het experimenteren!

## Containers: lists en dictionaries

Een variabelenaam per getal is natuurlijk niet handog meer als je met grotehoeveelheden getallen tegelijk werkt. Daarvoor stoppen we getallen die bij elkaar horen in een "container". Lists en dictionaries zijn daar voorbeelden van.

Een list is gewoon een lijst van allerlei variabelen. Hierin kun je echt alles stoppen: floating point getallen, integers, strings, andere lists en dictionaries en alle dingen die we later nog tegenkomen. Ook hierop kun je indices gebruiken zoals bij strings:

In [30]:
mijn_eerste_list = [1, 2.3, "stukje tekst", ["een", "lijst", "woorden"]]
print(mijn_eerste_list[0])
print(mijn_eerste_list[-1][1:])

1
['lijst', 'woorden']


Lists hebben een volgorde, dus de index van een bepaald element is vast. Dictionaries zijn wat dat betreft heel anders. Ze bestaan uit elementen die allemaal een "key/value"-paar zijn. De key is de naam van een element in de dictionary (vergelijkbaar met een index) en de value is de waarde. Net als in lists kunnen de waarden allerlei typen data door elkaar zijn. Keys kunnen gemaakt worden door getallen te gebruiken, maar ook strings en tuples. Tuples hebben we nog niet gezien maar zijn lists die niet te veranderen zijn ("immutable"):

In [2]:
mijn_eerste_tuple = (1, 2, 3.14, 'woord')
print(mijn_eerste_tuple)
print(mijn_eerste_tuple[0])
mijn_eerste_tuple[1] = 17

(1, 2, 3.14, 'woord')
1


TypeError: 'tuple' object does not support item assignment

In [3]:
mijn_eerste_dict = {'aap':'monkey', 'kip':'chicken', 3:'three', 'three':3, 'dict':{1:1, 2:2}}

Dictionaries zijn (voor technici) "hash tables" en een lookup is bijzonder snel, ook in heel grote dictionaries. Ook het testen van het bestaan van een key in een dictionary is eenvoudig en snel:

In [5]:
print(mijn_eerste_dict['three'])
'kip' in mijn_eerste_dict

3


True

## Intermezzo: Alles in Python is een "object"

Wat het precies betekent dat alles in Python een "object" is, is niet heel belangrijk op dit punt. Wat er wel erg handig aan is, is om te weten dat er allerlei "attributen" en "methoden" bestaan bij een object. Attributen zijn een soort "extra info" over het object (hier zien we later voorbeelden van). Methoden zijn functies die op het object kunnen worden losgelaten (bijvoorbeeld: maak van alle letters in de string hoofdletters). Het uitvoeren van een methode gebeurt dus net zoals bij andere functies ook met twee haakjes.

Om te zien wat er allemaal beschikbaar is voor het object in kwestie kun je de naam van het object typen dan een punt en dan tab (deze probeert "tab completion" en geeft alle opties). Voorbeeld:

In [29]:
print(mijn_eerste_string.upper)
print(mijn_eerste_string.upper())
?mijn_eerste_string.upper()

<built-in method upper of str object at 0x7f31141dd0d0>
PYTHON IS ECHT HEEL LEUK!


Docstring:
S.upper() -> str

Return a copy of S converted to uppercase.
Type:      builtin_function_or_method


Iets waar je je bedacht op moet zijn is dat de naam van een variabele eigenlijk een "pointer" is naar een object. Dus als je zegt "a = 5", dan wordt het object "5" aangemaakt in geheugen en de a is een pointer naar dat object. Dit heeft een verassend effect soms:

In [40]:
v = [0,0,0,0,0,0,0,0,0]
vec = v
vec[5] = 5

print(vec)
print(v)

print(vec == v)
print(vec is v)

[0, 0, 0, 0, 0, 5, 0, 0, 0]
[0, 0, 0, 0, 0, 5, 0, 0, 0]
True
True


In [42]:
v = [0,0,0,0,0,0,0,0,0]
vec = v[:]
vec[5] = 5
w = [0, 0, 0, 0, 0, 5, 0, 0, 0]

print(vec)
print(v)

print(vec == v)
print(vec == w)
print(vec is v)
print(vec is w)

[0, 0, 0, 0, 0, 5, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0]
False
True
False
False


In veel gevallen waarin je rekent met arrays van getallen en tabellen is dit ongewenst gedrag en is in de definitie van containers die we daar later voor gaan gebruiken ingebouwd dat een nieuwe verwijzing een kopie maakt, of in technische taal: een tweede instantie van hetzelfde object. In de praktijk zul je je hier dus niet zoveel zorgen meer over hoeven maken, maar het is goed om het in je achterhoofd te hebben.

## Loops en condities

Zoals bij veel programmeertalen kun je ook in Python gebruik maken van loops (door middel van "for" en "while") en condities ("if", "elif", "else"). For luidt een loop in met een vooraf gedefinieerd start- en eindpunt, while gaat door tot niet meer aan de conditie is voldaan. Bij beide kun je ook uit de loop springen met een break-statement. Het bereik van de code waarover de loop plaatsvindt wordt aangegeven met het indentatieniveau, er is dus geen statement om het eind van de geloopte code aan te geven en er staat niks tussen haakjes. Datzelfde geldt voor condities: als aan de conditie wordt voldaan, dan wordt alle code op 1 indentatieniveau dieper uitgevoerd. Dit scheelt een hoop typewerk en dwingt je tot het schrijven van nette, overzichtelijke code. Er is 1 uitzondering op die regel: als alles wat je in de loop of onder een bepaalde conditie wil doen op 1 regel past, dan kun je het gewoon achter de dubbele punt zetten, op dezelfde regel.


In [12]:
for i in (1, 2, 3, 4, 5, 6):
    print(i)
    if i*2 < 10:
        print("Ik mag lekker door!")
    elif i*2 > 10:
        print("Alleen precies tien is wat met deze statements nog niet is afgedekt.")
    else:
        break

print()

for ii in range(2,10,3): print(ii)        

print()

j = 0
while j < 100:
    j = (j+1) * 5
    print(j)

1
Ik mag lekker door!
2
Ik mag lekker door!
3
Ik mag lekker door!
4
Ik mag lekker door!
5

2
5
8

5
30
155


## List comprehension

Een efficiente manier om een functie te schrijven die op een list (of andere iterable) werkt en weer een list oplevert, is de list comprehension. Bijna in natuurlijke taal wordt een lijst gedefinieerd met een loop geschreven binnen de rechte haken van de list. Hier volgt een simpele en een iets complexere variant van een list comprehension. Gebruik deze wanneer het kan, dat laat zien dat je een echte Pythonista bent!

In [4]:
mooikort = [3*x for x in 'Python']
print(mooikort)
ingewikkelder = [2*x if not x**2 % 2 else 3*x for x in range(0,15,3)]
print(ingewikkelder)

['PPP', 'yyy', 'ttt', 'hhh', 'ooo', 'nnn']
[0, 9, 12, 27, 24]


## Functies definieren en gebruiken

Blokken code met een specifiek doel kun je veranderen in een functie die je dan kunt aanroepen, evetueel met verplichte parameters (ook wel "arguments" genoemd, of "args", waarvan de volgorde vastligt) en en optionele parameters (ook wel "keyword arguments" of "kwargs", waarvan de volgorde niet vastligt maar die je bij naam noemt) die eventueel een resultaat teruggeven. In het algemeen ziet de structuur van een functie er als volgt uit:

In [16]:
# Het definieren van deze waarden is alleen om de functiedefinitie te laten werken, 
# in de praktijk kan de functiedefinitie hardcoded waarden hebben.
defaultwaarde1 = 1
defaultwaarde2 = 2

def functienaam(parameter1, parameter2, optionele_parameter1=defaultwaarde1, optionele_parameter2=defaultwaarde2):
    """Documentatie over de functie in een docstring bovenaan de functie."""
    
    # code die alle input gebruikt
    resultaat = parameter1 + parameter2 + optionele_parameter1 + optionele_parameter2
    
    return resultaat
    

print(functienaam(12, 13))
print(functienaam(100, 200, optionele_parameter2=18))

28
319


In [17]:
?functienaam

Signature: functienaam(parameter1, parameter2, optionele_parameter1=1, optionele_parameter2=2)
Docstring: Documentatie over de functie in een docstring bovenaan de functie.
File:      ~/work/freelance/PyDataScienceIntroNL/<ipython-input-16-8b97fad5d865>
Type:      function


Het gebruik van functies kan op nog veel veelzijger wijze, maar die voeren te ver voor een introductie. Ben je benieuwd, zoek dan vooral de documentatie op!

## Functionaliteit importeren

Door anderen geschreven functionaliteiten (definities van objecten, variabelen en functies) kunnen worden geimporteerd als ze in een library of package zitten. Dat kan op meerdere manieren:

In [2]:
# Importeer 1 functie (sqrt()) uit een package (math):
from math import sqrt
# De functie sqrt() is nu beschikbaar.

# Importeer alles wat in de package math zit:
# from math import *
# Doe dit nooit, namespaces zijn een goed idee en dit maakt onduidelijk welke functionaliteit in de rest van de code waarvandaan komt.

# Importeer een heel package:
import math
# Alle functionaliteit is nu beschikbaar in de math namespace:
wortel9 = math.sqrt(9)

# Importeer ene package met kortere naam:
import math as m
# Alle functionaliteit is nu beschikbaar in de "m" namespace:
wortel2 = m.sqrt(2)


Het importeren van alle functionaliteiten doe je normaal gesproken allemaal in de bovenste code-cell van je notebook. Dit heeft meerdere voordelen, maar de belangrijkste zijn wel dat je zeker weet dat alle gebruikte packages zijn geinstalleerd en dat je bovenin al kan zien wat de dependencies van je notebook zijn.

## Numerical Python: numpy

Zo beginnen veel, zo niet alle, data science gerelateerde notebooks met een kort lijstje imports, waar numpy er een van is. Deze wordt door bijna iedereen op de wereld afgekort tot np. Zo zul je ook hulp op **StackOverflow** (als je dat nog niet kent: ga er eens kijken) voor numpy altijd onder np vinden. We houden ons hier uiteraard aan die conventie.

Numpy maakt gebruik van zogenaamde arrays. Deze lijken in de eerste plaats op lists, maar ze zijn heel wezenlijk anders:
- Binnen een array zijn alle elementen van hetzelfde data type (dus geen mix zoals in lists)
- Op arrays zijn de bewerkingen standaard array-operaties, wat betekent dat ze elementsgewijs worden uitgevoerd. Zo is, voor array a, 3*a gelijk aan een even lange array als a waarin alle elementen met 3 zijn vermenigvuldigd.

Enkele voorbeelden:

In [9]:
import numpy as np

mijn_eerste_array = np.array([1, 2, 3, 4])
print(mijn_eerste_array)

keer3 = mijn_eerste_array * 3
print(keer3)

print(mijn_eerste_array + np.array([40, 30, 20, 10]))

# Dingen die dus niet zouden kunnen, maar wel iets opleveren:
huh = np.array([1, 2, 'help'])
print(huh, "bestaat uit alleen maar strings omdat er daar minstens 1 van voorkomt!")

[1 2 3 4]
[ 3  6  9 12]
[41 32 23 14]
['1' '2' 'help'] bestaat uit alleen maar strings omdat er daar minstens 1 van voorkomt!


In [10]:
# Arrays kunnen meer dan 1 dimensie hebben
dim2 = np.array([[1 , 2],
                 [50, 60]])   # Deze mag je op 1 regel definieren, maar dit maakt het leesbaarder
print(dim2)

[[ 1  2]
 [50 60]]


In [11]:
# Op arrays zijn bijzonder veel bewrekingen gedefinieerd. Veel zijn methoden van het array object, maar numpy kent ook functies die geen methode zijn.

print("Het totaal van mijn eerste array is", mijn_eerste_array.sum())
print("Het gemiddelde van mijn eerste array is", mijn_eerste_array.mean())
print("De mediaan van mijn eerste array is", np.median(mijn_eerste_array))

Het totaal van mijn eerste array is 10
Het gemiddelde van mijn eerste array is 2.5
De mediaan van mijn eerste array is 2.5


In [12]:
# Op twee- en hogerdimensionale arrays kun je zulke dingen over de hele array, of langs de rijen of kolommen doen:
print("De verschillende sommen van dim2:")
print(dim2.sum())
print(dim2.sum(axis=0))
print(dim2.sum(axis=1))

De verschillende sommen van dim2:
113
[51 62]
[  3 110]


Tenslotte heeft numpy een enorme berg aan functionaliteit. Ik raad je van harte aan eens te kijken op de website wat er allemaal mogelijk is: http://www.numpy.org/

## Referenties naar literatuur over de stof van hierboven en nog veel meer van de komende weken:

Python Data Science Handbook (en al het andere youtube- en blogmateriaal van auteur Jake VanderPlas, zie http://jakevdp.github.io/), geheel in notebooks op github: https://jakevdp.github.io/PythonDataScienceHandbook/. Het pandas boek van Wes McKinney: https://github.com/wesm/pydata-book

Antwoorden op al je vragen (of ze staan er al, of je hebt ze snel) op StackOverflow: https://stackoverflow.com/

Documentatie van de voor data science belangrijke paketten: https://docs.scipy.org/doc/, http://pandas.pydata.org/pandas-docs/stable/

Voor visualisatie gebruiken we matplotlib (https://matplotlib.org/ en de gallery op https://matplotlib.org/gallery/index.html), seaborn (https://seaborn.pydata.org/) en bokeh (https://bokeh.pydata.org/en/latest/).

Verder vind je op YouTube veel praatjes en workshops (vaak met materiaal op github). Let er wel op dat je redelijk recent materiaal bekijkt, sommige van deze paketten zijn nog stevig in ontwikkeling. Op YouTube kun je zoeken naar PyData, (Euro)SciPy, Pycon, Enthought en Numfocus. Dat geeft je een hele hoop materiaal.