In [2]:
import numpy as np
import pandas as pd

Opdracht over vstack en hstack als toevoeging op np.concatenate

Broadcasting with row and column vector:


In [3]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)



[0 1 2]
[[0]
 [1]
 [2]]


In [4]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])